version: "3"
networks: 
  bitcoin_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  bitcoind:
    restart: unless-stopped
    container_name: bitcoind
    networks: 
      bitcoin_net:
        ipv4_address: 172.20.0.4
    build:
      context: "./bitcoind"
      dockerfile: "Dockerfile"
    expose:
    - "8832"
    - "8333"
    - "28332"
    - "28333"
    - "28334"
    volumes:
    - "/media/rich/experiments/bitcoin:/data"
#    - "bitcoin_wallet_datadir:/walletdata"
    - "tor_datadir:/home/tor/.tor"
    links:
    - tor
  lnd_bitcoin:
    container_name: lnd
    build:
      context: "./lnd"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    networks: 
      bitcoin_net:
        ipv4_address: 172.20.0.5
    ports:
    - "9735:9735"
    expose:
    - "8080"
    - "8081"
    - "9735"
    volumes:
    - "lnd_bitcoin_datadir:/data"
    - "lndloop_bitcoin_datadir:/root/.loop/${NBITCOIN_NETWORK:-regtest}"
    - "/media/rich/experiments/bitcoin:/deps/.bitcoin"
    - "tor_datadir:/home/tor/.tor"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
    links:
    - bitcoind
    - tor
#   bitcoin_thub:
#     image: apotdevin/thunderhub:base-v0.12.17@sha256:a5f85ee15c5d8f31630c28c702a035b2b2a50b5ac2145eb1f6ce0e4c1c69bdc9
#     restart: unless-stopped
#     networks: 
#       bitcoin_net:
#         ipv4_address: 172.20.0.6
#     stop_signal: SIGKILL
#     environment:
#       NO_VERSION_CHECK: "true"
#       COOKIE_PATH: "/data/.cookie"
#       SSO_SERVER_URL: "lnd_bitcoin:10009"
#       SSO_MACAROON_PATH: "/etc/lnd"
#       SSO_CERT_PATH: "/etc/lnd/tls.cert"
#       NO_CLIENT_ACCOUNTS: "true"
#       LOG_LEVEL: debug
#       LOGOUT_URL: "/server/services/thunderhub/BTC"
#       TOR_PROXY_SERVER: socks://tor:9050
#     volumes:
#     - "lnd_bitcoin_datadir:/etc/lnd"
#     - "lnd_bitcoin_thub_datadir:/data"
#     expose:
#     - "3000"
#     command: ["npm", "run", "start:cookie", "--", "/data/.cookie"]
#     links:
#     - lnd_bitcoin
  tor:
    build:
      context: "./tor"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    networks: 
      bitcoin_net:
        ipv4_address: 172.20.0.2
    container_name: tor
    environment:
      TOR_PASSWORD: btcpayserver
    expose:
    - "9050"
    - "9051"
    volumes:
    - "tor_datadir:/home/tor/.tor"
    - "tor_torrcdir:/usr/local/etc/tor"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
 
volumes:
  #"/media/rich/experiments/bitcoin:bitcoin_datadir"
  #bitcoin_wallet_datadir: 
  lnd_bitcoin_datadir: 
  lndloop_bitcoin_datadir: 
  lnd_bitcoin_rtl_datadir: 
  lnd_bitcoin_thub_datadir: 
  tor_datadir: 
  tor_torrcdir: 
  tor_servicesdir: 
